modLoader="javafml"
loaderVersion="[34,)"
license="MIT"
issueTrackerURL="https://github.com/TheLMiffy1111/PackagedAuto/issues"

[[mods]]
	modId = "packagedauto"
	version = "0@VERSION@"
	displayName = "PackagedAuto"
	description = "An Applied Energistics 2 addon that uses 'packages' to allow autocrafting with more than 9 items."
	logoFile = "packagedauto.logo.png"
	authors = "TheLMiffy1111"
	displayURL = "https://www.curseforge.com/minecraft/mc-mods/packagedauto"

[[dependencies.packagedauto]]
	modId="forge"
	versionRange="[34,)"
	mandatory=true

[[dependencies.packagedauto]]
	modId="ae2"
	versionRange="[8,)"
	mandatory=false
